/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_tipo_cambio extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    DefaultTableModel mostrar;
    //Variables 
    String fecha;
    int moneda;
    Double pvta;
    Double pcom;

    /**
     * Creates new form frm_tipo_cambio
     */
    public frm_tipo_cambio() {
        initComponents();
        txt_fec.setText(ven.fechaformateada(ven.getFechaActual()));
        ver_monedas();
        ver_cambios();
    }

    private void ver_monedas() {
        try {
            ArrayList array_mon = new ArrayList();
            Statement st = con.conexion();
            String query = "select nombre from moneda order by idmoneda asc";
            ResultSet rs = con.consulta(st, query);
            while (rs.next()) {
                array_mon.add(rs.getString("nombre"));
            }
            if (array_mon.size() > 0) {
                for (Object object_mon : array_mon) {
                    cbx_mon.addItem(object_mon);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Lista no disponible");
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
    }

    private void ver_cambios() {
        mostrar = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        mostrar.addColumn("Fecha");
        mostrar.addColumn("Moneda");
        mostrar.addColumn("P. Vta.");
        mostrar.addColumn("P. Com.");
        try {
            Statement st = con.conexion();
            String ver_cam = "select tc.fecha, m.nombre, tc.compra, tc.venta from tipo_cambio as tc inner join moneda as m on tc.idmon = m.idmoneda where "
                    + "month(tc.fecha) = month(current_date()) order by tc.fecha desc";
            ResultSet rs = con.consulta(st, ver_cam);
            Object fila[] = new Object[4];
            while (rs.next()) {
                fila[0] = ven.fechaformateada(rs.getString("fecha"));
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("venta");
                fila[3] = rs.getString("compra");
                mostrar.addRow(fila);
            }
            con.cerrar(rs);
            con.cerrar(st);

        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        }
        t_cambio.setModel(mostrar);
        t_cambio.getColumnModel().getColumn(0).setPreferredWidth(80);
        t_cambio.getColumnModel().getColumn(1).setPreferredWidth(80);
        t_cambio.getColumnModel().getColumn(2).setPreferredWidth(50);
        t_cambio.getColumnModel().getColumn(3).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_fec = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ven = new javax.swing.JTextField();
        txt_com = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_cambio = new javax.swing.JTable();
        btn_cer = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_edi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbx_mon = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Tipo de Cambio a Soles");

        jLabel2.setText("Fecha");

        try {
            txt_fec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fecKeyPressed(evt);
            }
        });

        jLabel3.setText("P. Venta:");

        jLabel4.setText("P. Compra:");

        txt_ven.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_ven.setEnabled(false);
        txt_ven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_venKeyPressed(evt);
            }
        });

        txt_com.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_com.setEnabled(false);
        txt_com.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_comKeyPressed(evt);
            }
        });

        t_cambio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_cambio);

        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        btn_add.setText("Agregar");
        btn_add.setEnabled(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edi.setText("Editar");
        btn_edi.setEnabled(false);

        jLabel1.setText("Moneda:");

        cbx_mon.setEnabled(false);
        cbx_mon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_monKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_add))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_ven, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_com, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_edi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_cer, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbx_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_com, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fecKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec.getText().length() == 10) {
                cbx_mon.setEnabled(true);
                cbx_mon.setSelectedIndex(2);
                cbx_mon.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fecKeyPressed

    private void txt_venKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_venKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_ven.getText().length() > 1) {
                txt_com.setEnabled(true);
                txt_com.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_venKeyPressed

    private void txt_comKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_comKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_com.getText().length() > 1) {
                btn_add.setEnabled(true);
                btn_add.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_comKeyPressed

    private void llenar() {
        fecha = ven.fechabase(txt_fec.getText());
        moneda = cbx_mon.getSelectedIndex() + 1;
        pvta = Double.parseDouble(txt_ven.getText());
        pcom = Double.parseDouble(txt_com.getText());
    }

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        llenar();
        boolean existe = existe_tc(fecha, moneda + "");
        if (existe == false) {
            Statement st = con.conexion();
            String ins_cam = "insert into tipo_cambio Values ('" + fecha + "', '" + moneda + "', '" + pvta + "', '" + pcom + "')";
            System.out.println(ins_cam);
            con.actualiza(st, ins_cam);
            con.cerrar(st);
            ver_cambios();
            txt_fec.setEnabled(true);
            txt_ven.setEnabled(false);
            txt_ven.setText("");
            txt_com.setText("");
            txt_com.setEnabled(false);
            txt_fec.requestFocus();
        }

        if (existe == true) {
            Statement st = con.conexion();
            String ins_cam = "update tipo_cambio set idmon = '" + moneda + "', venta =  '" + pvta + "', compra = '" + pcom + "' where fecha = '" + fecha + "'";
            System.out.println(ins_cam);
            con.actualiza(st, ins_cam);
            con.cerrar(st);
            ver_cambios();
            txt_fec.setEnabled(true);
            txt_ven.setEnabled(false);
            txt_ven.setText("");
            txt_com.setText("");
            txt_com.setEnabled(false);
            txt_fec.requestFocus();
        }
        
        btn_cer.doClick();
    }//GEN-LAST:event_btn_addActionPerformed

    private boolean existe_tc(String fecha, String idmon) {
        boolean tc = false;
        try {
            Statement st = con.conexion();
            String ver_tc = "select venta from tipo_cambio where fecha = '" + fecha + "' and idmon = '" + idmon + "'";
            ResultSet rs = con.consulta(st, ver_tc);
            if (rs.next()) {
                tc = true;
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
        return tc;
    }
    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void cbx_monKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_monKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cbx_mon.getSelectedIndex() != 1) {
                txt_ven.setEnabled(true);
                txt_ven.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUEDE SELECCIONAR SOLES");
            }
        }
    }//GEN-LAST:event_cbx_monKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_edi;
    private javax.swing.JComboBox cbx_mon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_cambio;
    private javax.swing.JTextField txt_com;
    private javax.swing.JFormattedTextField txt_fec;
    private javax.swing.JTextField txt_ven;
    // End of variables declaration//GEN-END:variables
}
