/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Cl_Albaran;
import Clases.Cl_Conectar;
import Clases.Cl_Productos;
import Clases.Cl_Tipo_Documentos;
import Clases.Cl_Varios;
import Vistas.frm_ver_prod_alm;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sonomusic.frm_menu;
import Vistas.frm_ver_guias;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.HeadlessException;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author pc
 */
public final class frm_reg_traslado_almacen extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    Cl_Albaran alb = new Cl_Albaran();
    Cl_Productos pro = new Cl_Productos();
    Cl_Tipo_Documentos tido = new Cl_Tipo_Documentos();
    public static DefaultTableModel detalle;
    public static int idsol = 0;
    public static int idtras = 0;
    public static String accion = "traslado";
    Integer i;

    /**
     * Creates new form frm_traslado_almacen
     */
    public frm_reg_traslado_almacen() {
        initComponents();

        cargar_productos_txt();

        txt_fec.setText(ven.fechaformateada(ven.getFechaActual()));

        String almacen = "select nom_alm from almacen order by idAlmacen asc";
        ver_almacen(almacen);

        txt_partida.setText(frm_menu.alm.getDireccion().toUpperCase());

        String documentos = "select desc_tipd from tipo_doc order by idtipo_doc asc";
        ver_documentos(documentos);

        cbx_documento.setSelectedIndex(4);

        detalle = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        detalle.addColumn("Id");
        detalle.addColumn("Descripcion");
        detalle.addColumn("Marca");
        detalle.addColumn("C. Act.");
        detalle.addColumn("Cant.");
        detalle.addColumn("Und. Med");
        t_detalle.setModel(detalle);
        t_detalle.getColumnModel().getColumn(0).setPreferredWidth(10);
        t_detalle.getColumnModel().getColumn(1).setPreferredWidth(350);
        t_detalle.getColumnModel().getColumn(2).setPreferredWidth(30);
        t_detalle.getColumnModel().getColumn(3).setPreferredWidth(30);
        t_detalle.getColumnModel().getColumn(4).setPreferredWidth(30);
        t_detalle.getColumnModel().getColumn(5).setPreferredWidth(30);
        detalle.fireTableDataChanged();
        ven.centrar_celda(t_detalle, 0);
        ven.centrar_celda(t_detalle, 2);
        ven.derecha_celda(t_detalle, 3);
        ven.derecha_celda(t_detalle, 4);
        ven.centrar_celda(t_detalle, 5);

    }

    private void ver_almacen(String query) {
        try {
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);

            while (rs.next()) {
                String fila;
                fila = rs.getString("nom_alm");
                cbx_alm_de.addItem(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException e) {
            System.out.print(e);
        }
    }

    private void ver_documentos(String query) {
        try {
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);

            while (rs.next()) {
                String fila;
                fila = rs.getString("desc_tipd");
                cbx_documento.addItem(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_transportista = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_marca1 = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_placa1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rbt_si = new javax.swing.JRadioButton();
        rbt_no = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        txt_ruc_transporte = new javax.swing.JTextField();
        txt_razon_transporte = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txt_brevete = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_inscripcion = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_chofer1 = new javax.swing.JTextField();
        j_productos = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_productos = new javax.swing.JTable();
        btn_cer1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_cc = new javax.swing.JButton();
        btn_el = new javax.swing.JButton();
        btn_enviar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbx_documento = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_ser = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_fec = new javax.swing.JFormattedTextField();
        lbl_tienda = new javax.swing.JLabel();
        cbx_alm_de = new javax.swing.JComboBox();
        txt_ruc_alm = new javax.swing.JTextField();
        txt_raz_alm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_cer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_motivo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_partida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_llegada = new javax.swing.JTextField();
        btn_transportista = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_detalle = new javax.swing.JTable();
        txt_buscar_producto = new javax.swing.JTextField();
        btn_recibir = new javax.swing.JButton();
        btn_verificar = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Vehiculo"));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Marca:");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modelo:");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Placa:");

        txt_marca1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_placa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel24.setText("Vehiculo Externo??");

        rbt_si.setText("Si");

        rbt_no.setText("No");

        jLabel25.setText("RUC:");

        txt_ruc_transporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_placa1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_marca1))
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ruc_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(41, 41, 41)
                        .addComponent(rbt_si)
                        .addGap(18, 18, 18)
                        .addComponent(rbt_no)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_razon_transporte)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt_si, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ruc_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_placa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_razon_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Chofer"));

        jLabel26.setText("Brevete:");

        txt_brevete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setText("Certificado de Inscripcion:");

        txt_inscripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel28.setText("Chofer:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_brevete, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel27)
                        .addGap(32, 32, 32)
                        .addComponent(txt_inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(txt_chofer1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_brevete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_chofer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_transportistaLayout = new javax.swing.GroupLayout(jd_transportista.getContentPane());
        jd_transportista.getContentPane().setLayout(jd_transportistaLayout);
        jd_transportistaLayout.setHorizontalGroup(
            jd_transportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transportistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_transportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_transportistaLayout.setVerticalGroup(
            jd_transportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transportistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setForeground(new java.awt.Color(212, 2, 2));
        jLabel6.setText("Buscar:");

        txt_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busquedaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busquedaKeyTyped(evt);
            }
        });

        jLabel13.setText("encontrados");

        jScrollPane2.setBackground(new java.awt.Color(254, 254, 254));

        t_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        t_productos.setRowHeight(20);
        t_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_productosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_productosMousePressed(evt);
            }
        });
        t_productos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_productosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(t_productos);

        btn_cer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer1.setText("Cerrar");
        btn_cer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cer1ActionPerformed(evt);
            }
        });

        jLabel14.setText("0");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setText("Esc - Limpiar Busqueda");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Flecha Arriba y Abajo - Subir y Bajar en Cuadro");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel3.setText("Enter - Busca / Seleccionar Producto");

        javax.swing.GroupLayout j_productosLayout = new javax.swing.GroupLayout(j_productos.getContentPane());
        j_productos.getContentPane().setLayout(j_productosLayout);
        j_productosLayout.setHorizontalGroup(
            j_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(j_productosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                        .addComponent(btn_cer1))
                    .addGroup(j_productosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        j_productosLayout.setVerticalGroup(
            j_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btn_cer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(254, 254, 254));
        setClosable(true);
        setTitle("Traslado entre Almacenes");
        setMaximumSize(new java.awt.Dimension(800, 600));

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delivery.png"))); // NOI18N
        btn_add.setText("Agregar Productos");
        btn_add.setEnabled(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_cc.setText("+/-");
        btn_cc.setEnabled(false);
        btn_cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ccActionPerformed(evt);
            }
        });

        btn_el.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bin_closed.png"))); // NOI18N
        btn_el.setText("Eliminar");
        btn_el.setEnabled(false);
        btn_el.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elActionPerformed(evt);
            }
        });

        btn_enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delivery.png"))); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.setEnabled(false);
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));
        jPanel1.setForeground(new java.awt.Color(212, 2, 2));

        jLabel17.setForeground(java.awt.Color.red);
        jLabel17.setText("Tipo Documento:");

        cbx_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_documentoKeyPressed(evt);
            }
        });

        jLabel18.setForeground(java.awt.Color.red);
        jLabel18.setText("Serie:");

        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText("Numero:");

        txt_ser.setEditable(false);
        txt_ser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ser.setText("0");
        txt_ser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serKeyPressed(evt);
            }
        });

        txt_num.setEditable(false);
        txt_num.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_num.setText("0");

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Fecha");

        try {
            txt_fec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec.setEnabled(false);
        txt_fec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecActionPerformed(evt);
            }
        });
        txt_fec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fecKeyPressed(evt);
            }
        });

        lbl_tienda.setForeground(java.awt.Color.red);
        lbl_tienda.setText("Tienda Destino");

        cbx_alm_de.setEnabled(false);
        cbx_alm_de.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_alm_deKeyPressed(evt);
            }
        });

        txt_ruc_alm.setEditable(false);
        txt_ruc_alm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_raz_alm.setEditable(false);

        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("Datos Tienda:");

        btn_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("Motivo:");

        txt_motivo.setEditable(false);
        txt_motivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_motivo.setText("0");
        txt_motivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_motivoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cbx_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_ser)
                            .addGap(96, 96, 96)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tienda)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbx_alm_de, 0, 125, Short.MAX_VALUE)
                            .addComponent(txt_ruc_alm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(btn_cer))
                    .addComponent(txt_raz_alm)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(82, 82, 82)
                        .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_alm_de, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ruc_alm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_raz_alm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direcciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));

        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setText("Punto de Partida:");

        txt_partida.setEditable(false);
        txt_partida.setFocusable(false);

        jLabel20.setForeground(java.awt.Color.red);
        jLabel20.setText("Punto de Llegada:");

        txt_llegada.setEditable(false);
        txt_llegada.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel20))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_partida)
                    .addComponent(txt_llegada))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_partida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_transportista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carro.png"))); // NOI18N
        btn_transportista.setText("Transportista");
        btn_transportista.setEnabled(false);
        btn_transportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transportistaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle del Traslado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));

        t_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_detalleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_detalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_detalle);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_buscar_producto.setToolTipText("Escribir para buscar Productos");
        txt_buscar_producto.setEnabled(false);
        txt_buscar_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscar_productoKeyPressed(evt);
            }
        });

        btn_recibir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/compra_producto.png"))); // NOI18N
        btn_recibir.setText("Recibir");
        btn_recibir.setEnabled(false);
        btn_recibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recibirActionPerformed(evt);
            }
        });

        btn_verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/arrow_redo.png"))); // NOI18N
        btn_verificar.setText("Verificar Cantidad");
        btn_verificar.setEnabled(false);
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_el)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_verificar)
                        .addGap(145, 145, 145)
                        .addComponent(btn_recibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_enviar)
                        .addGap(11, 11, 11))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_transportista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar_producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_transportista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_el, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_recibir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        accion = "";
        frm_ver_guias guias = new frm_ver_guias();
        ven.llamar_ventana(guias);
        this.dispose();

    }//GEN-LAST:event_btn_cerActionPerformed

    void contar_filas() {
        int contar_filas = t_detalle.getRowCount();
        if (contar_filas == 29) {
            txt_buscar_producto.setEnabled(false);
            JOptionPane.showMessageDialog(null, "SE HA LLEGADO AL LIMITE DE 30 PRODUCTOS");
        }
    }

    void cargar_productos_txt() {
        try {
            // autocompletar = new TextAutoCompleter(txt_buscar_producto);
            TextAutoCompleter autocompletar = new TextAutoCompleter(txt_buscar_producto, new AutoCompleterCallback() {
                @Override
                public void callback(Object selectedItem) {
                    txt_buscar_producto.setText("");
                    txt_buscar_producto.requestFocus();
                    String cadena = selectedItem.toString();
                    JOptionPane.showMessageDialog(null, "El usuario seleccionó: " + cadena);
                    if (cadena.length() > 0) {
                        boolean contiene_guion = false;
                        for (int j = 0; j < cadena.length(); j++) {
                            if (cadena.charAt(j) == '-') {
                                contiene_guion = true;
                            }
                        }
                        if (contiene_guion == true) {
                            contiene_guion = false;
                            String[] array_producto = cadena.split("-");
                            String id_producto = array_producto[0].trim();
                            //JOptionPane.showMessageDialog(null, "El id del Producto es : " + id_producto);

                            try {
                                Statement st = con.conexion();
                                String ver_producto = "select p.idProductos, p.desc_pro, p.modelo, p.serie, p.marca, pa.cant, p.cant_min, pa.precio, p.estado, c.desc_clas, "
                                        + "u.desc_und, p.grado from producto_almacen as pa inner join productos as p on pa.idProductos=p.idProductos "
                                        + "inner join clasificacion as c on p.id_clas=c.id_clas inner join und_medida as u on "
                                        + "p.idUnd_Medida=u.idUnd_Medida where pa.idAlmacen = '" + frm_menu.alm.getId() + "' and p.idProductos = '" + id_producto + "'";
                                System.out.println(ver_producto);
                                ResultSet rs = con.consulta(st, ver_producto);
                                if (rs.next()) {
                                    Object fila[] = new Object[6];
                                    fila[0] = id_producto;
                                    fila[1] = rs.getString("desc_pro") + " " + rs.getString("marca") + " " + rs.getString("modelo") + " " + rs.getString("serie");
                                    fila[2] = rs.getString("marca");
                                    double cantidad = rs.getDouble("cant");
                                    fila[3] = ven.formato_numero(cantidad);
                                    String texto = JOptionPane.showInputDialog("Ingrese Cantidad");
                                    double cantidad_nueva = 1;
                                    if (texto != null) {
                                        if (ven.esDecimal(texto)) {
                                            cantidad_nueva = Double.parseDouble(texto);
                                            // if (cantidad >= cantidad_nueva) {
                                            fila[4] = ven.formato_numero(cantidad_nueva);
                                            /* } else {
                                             double exceso = cantidad_nueva - cantidad;
                                             cantidad_nueva = cantidad;
                                             fila[4] = ven.formato_numero(cantidad_nueva);
                                             JOptionPane.showMessageDialog(null, "NO HAY DEMASIADOS PRODUCTOS \n EXCESO DE " + exceso + " UNIDADES");
                                             }*/
                                        } else {
                                            fila[4] = ven.formato_numero(cantidad_nueva);
                                        }
                                    } else {
                                        fila[4] = ven.formato_numero(cantidad_nueva);
                                    }
                                    fila[5] = rs.getString("desc_und");

                                    //if (cantidad > 0.0) {
                                    valida_tabla(Integer.parseInt(id_producto), fila);
                                    btn_enviar.setEnabled(true);
                                    //} else {
                                    //    JOptionPane.showMessageDialog(null, "No existe suficiente cantidad para agregar el producto.");
                                    //}
                                }

                                con.cerrar(rs);
                                con.cerrar(st);

                            } catch (SQLException | HeadlessException e) {
                                System.out.println(e);
                                JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
                            }

                            txt_buscar_producto.setText("");
                            txt_buscar_producto.requestFocus();

                        }
                        if (contiene_guion == false) {
                            txt_buscar_producto.setText("");
                            txt_buscar_producto.requestFocus();
                        }

                    }
                }
            });

            autocompletar.setMode(0);
            autocompletar.setCaseSensitive(false);
            Statement st = con.conexion();
            String sql = "select pa.idProductos,p.desc_pro, p.marca, p.modelo, p.serie, pa.cant, pa.precio"
                    + " from producto_almacen as pa inner join productos as p"
                    + " on pa.idProductos=p.idProductos where pa.idAlmacen ='" + frm_menu.alm.getId() + "' "
                    + "order by p.desc_pro asc, p.modelo asc";
            ResultSet rs = con.consulta(st, sql);
            while (rs.next()) {
                autocompletar.addItem(rs.getString("pa.idProductos") + " - " + rs.getString("p.desc_pro") + " " + rs.getString("p.marca") + " " + rs.getString("p.modelo")
                        + " -- Cant.: " + rs.getString("pa.cant"));
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getLocalizedMessage());
            System.out.println(e.getLocalizedMessage());
        }
    }

    private void valida_tabla(int producto, Object[] objeto) {
        //estado de ingreso
        boolean ingresar = false;
        int cuenta_iguales = 0;

        //verificar fila no se repite
        int contar_filas = t_detalle.getRowCount();
        if (contar_filas == 0) {
            ingresar = true;
        }

        if (contar_filas > 0) {
            for (int j = 0; j < contar_filas; j++) {
                int id_producto_fila = Integer.parseInt(t_detalle.getValueAt(j, 0).toString());
                if (producto == id_producto_fila) {
                    ingresar = false;
                    cuenta_iguales++;
                    JOptionPane.showMessageDialog(null, "El Producto a Ingresar ya existe en la lista");
                } else {
                    ingresar = true;
                }
            }
        }

        if (ingresar == true && cuenta_iguales == 0) {
            detalle.addRow(objeto);
            t_detalle.setModel(detalle);
            // contar_filas = t_detalle.getRowCount();
            contar_filas();
//            String texto = JOptionPane.showInputDialog("Ingrese Cantidad");
//            if (texto != null) {
//                if (ven.esDecimal(texto)) {
//                    double cantidad = Double.parseDouble(texto);
//                    Double cantidad_actual = Double.parseDouble(t_detalle.getValueAt(contar_filas - 1, 2).toString());
//                    if (cantidad_actual >= cantidad) {
//                        t_detalle.setValueAt(ven.formato_numero(cantidad), contar_filas - 1, 3);
//                    } else {
//                        JOptionPane.showMessageDialog(null, "NO PUEDE SOBREPASAR CANTIDAD ACTUAL");
//                    }
//                    calcular_total();
//                }
//            }
        }
    }

    private void txt_serKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_num.setEditable(true);
            txt_num.requestFocus();
        }
    }//GEN-LAST:event_txt_serKeyPressed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        j_productos.setModal(true);
        j_productos.setSize(1000, 450);
        j_productos.setLocationRelativeTo(null);
        String query = "select p.idProductos, p.desc_pro, p.modelo, p.serie, p.marca, pa.cant, p.cant_min, pa.precio, p.estado, c.desc_clas, "
                + "u.desc_und, p.grado from producto_almacen as pa inner join productos as p on pa.idProductos=p.idProductos "
                + "inner join clasificacion as c on p.id_clas=c.id_clas inner join und_medida as u on "
                + "p.idUnd_Medida=u.idUnd_Medida where pa.idAlmacen = '" + frm_menu.alm.getId() + "' order by p.desc_pro asc limit 0";
        pro.mostrar_productos(query, t_productos);
        j_productos.setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void t_detalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_detalleMousePressed
        i = t_detalle.getSelectedRow();
        if (accion.equals("registrar")) {
            btn_el.setEnabled(true);
            btn_cc.setEnabled(true);
        }
    }//GEN-LAST:event_t_detalleMousePressed

    private void btn_elActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elActionPerformed
        detalle.removeRow(i);
    }//GEN-LAST:event_btn_elActionPerformed

    private void btn_ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ccActionPerformed
        Double cantidad = Double.parseDouble(JOptionPane.showInputDialog("Ingrese Cantidad"));
        t_detalle.setValueAt(cantidad, i, 3);
    }//GEN-LAST:event_btn_ccActionPerformed

    private void datos_tienda(int id_almacen) {
        try {
            Statement st = con.conexion();
            String ver_dir = "select * from almacen where idAlmacen='" + id_almacen + "'";
            ResultSet rs = con.consulta(st, ver_dir);
            if (rs.next()) {
                txt_ruc_alm.setText(rs.getString("ruc"));
                txt_raz_alm.setText(rs.getString("raz_soc"));
                txt_llegada.setText(rs.getString("dir_alm"));
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    private void llenar() {
        alb.setFecha(ven.fechabase(txt_fec.getText()));
        alb.setMotivo("TRASLADO");
        try {
            Integer id = frm_menu.alm.getId();
            Statement st = con.conexion();
            String ver_dir = "select dir_alm from almacen where idAlmacen='" + id + "'";
            ResultSet rs = con.consulta(st, ver_dir);
            if (rs.next()) {
                alb.setOrigen(rs.getString("dir_alm"));
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (SQLException ex) {
            System.out.print(ex);
        }

        try {
            Integer id = cbx_alm_de.getSelectedIndex() + 1;
            Statement st = con.conexion();
            String ver_dir = "select dir_alm from almacen where idAlmacen='" + id + "'";
            ResultSet rs = con.consulta(st, ver_dir);
            if (rs.next()) {
                alb.setDestino(rs.getString("dir_alm"));
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (SQLException ex) {
            System.out.print(ex);
        }
        tido.setId(cbx_documento.getSelectedIndex() + 1);
        alb.setSer(Integer.parseInt(txt_ser.getText()));
        alb.setNro(Integer.parseInt(txt_num.getText()));
        tido.setSerie(Integer.parseInt(txt_ser.getText()));
        tido.setNro(Integer.parseInt(txt_num.getText()));
        alb.setBrevete(txt_brevete.getText());
        alb.setRuc_tran(txt_ruc_transporte.getText());
        alb.setRaz_tran(txt_razon_transporte.getText());
        alb.setChofer(txt_chofer1.getText());
        alb.setConstancia(txt_inscripcion.getText());
        alb.setMarca(txt_marca1.getText());
        alb.setPlaca(txt_placa1.getText());
    }


    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        btn_enviar.setEnabled(false);
        llenar();
        Integer alm_or = frm_menu.alm.getId();
        Integer alm_de = cbx_alm_de.getSelectedIndex() + 1;
        Double cant_act = 0.00;
        Double nueva_cant = 0.00;
        String ruc = "";
        String raz = "";
        String dir = "";
        if (accion.equals("registrar")) {
            String almacen = "HACIA TIENDA " + cbx_alm_de.getSelectedItem().toString();
            try {
                int idalma = cbx_alm_de.getSelectedIndex() + 1;
                Statement st = con.conexion();
                String ver_emp = "select * from almacen where idAlmacen = '" + idalma + "'";
                ResultSet rs = con.consulta(st, ver_emp);
                if (rs.next()) {
                    ruc = rs.getString("ruc");
                    raz = rs.getString("raz_soc");
                    dir = rs.getString("dir_alm");
                }
                con.cerrar(rs);
                con.cerrar(st);
            } catch (SQLException ex) {
                System.out.print(ex);
            }
            int registrar = -1;
            try {
                Statement st = con.conexion();
                String ins_tras = "insert into traslado Values (null, '" + alb.getFecha() + "', '" + alb.getMotivo() + "', "
                        + "'" + alb.getOrigen() + "', '" + alb.getDestino() + "', '" + ruc + "', '" + raz + "', '" + frm_menu.usu.getNick() + "',"
                        + "'" + tido.getId() + "', '" + alb.getNro() + "', '" + alb.getSer() + "', '0', '" + alb.getRuc_tran() + "', '" + alb.getRaz_tran() + "', '" + alb.getMarca() + "'"
                        + ", '" + alb.getPlaca() + "', '" + alb.getBrevete() + "', '" + alb.getConstancia() + "', '" + alb.getChofer() + "')";
                registrar = con.actualiza(st, ins_tras);
                con.cerrar(st);
            } catch (Exception ex) {
                System.out.print(ex);
            }
            if (registrar > -1) {
                try {
                    Statement st = con.conexion();
                    String ver_tras = "select idTraslado from traslado where nick = '" + frm_menu.lbl_user.getText() + "' and ruc_dest = '" + ruc + "' order by idTraslado desc limit 1";
                    ResultSet rs = con.consulta(st, ver_tras);
                    if (rs.next()) {
                        alb.setId(rs.getInt("idTraslado"));
                    }
                    con.cerrar(rs);
                    con.cerrar(st);
                } catch (SQLException ex) {
                    System.out.print(ex);
                }
                /*
                 if (idsol != 0) {
                 System.out.println("idsolicitud" + idsol);
                 String fecha1 = ven.fechabase(txt_fec.getText());
                 System.out.println(alb.getFecha());
                 try {
                 Statement st = con.conexion();
                 String upd_sol = "update solicitud_articulos set estado = '1', fec_env = '" + fecha1 + "' where idsolicitud = '" + idsol + "'";
                 con.actualiza(st, upd_sol);
                 con.cerrar(st);
                 } catch (Exception e) {
                 System.out.println(e);
                 }

                 }
                 */
                //leer filas de tabla
                Integer filas = t_detalle.getRowCount();
                for (int x = 0; x < filas; x++) {
                    pro.setId_pro(Integer.parseInt(t_detalle.getValueAt(x, 0).toString()));
                    pro.setCan(Double.parseDouble(t_detalle.getValueAt(x, 4).toString()));

                    try {
                        Statement st = con.conexion();
                        String ver_pro_alm = "select costo_compra from productos where idProductos = '" + pro.getId_pro() + "'";
                        ResultSet rs = con.consulta(st, ver_pro_alm);
                        if (rs.next()) {
                            pro.setCos_pro(rs.getDouble("costo_compra"));
                        }
                        con.cerrar(rs);
                        con.cerrar(st);
                    } catch (SQLException ex) {
                        System.out.print(ex);
                    }

                    //registrar detalle de traslado
                    try {
                        Statement st = con.conexion();
                        String ins_tras = "insert into productos_traslado Values ('" + alb.getId() + "', '" + pro.getId_pro() + "', '" + pro.getCan() + "', '0')";
                        con.actualiza(st, ins_tras);
                        con.cerrar(st);
                    } catch (Exception ex) {
                        System.out.print(ex);
                    }

                    //registrar retiro de primer almacen (actualizar cantidades)
                    try {
                        Statement st = con.conexion();
                        String ver_pro_alm = "select cant from producto_almacen where idAlmacen = '" + alm_or + "' and idProductos= '" + pro.getId_pro() + "'";
                        ResultSet rs = con.consulta(st, ver_pro_alm);
                        if (rs.next()) {
                            cant_act = rs.getDouble("cant");
                        } else {
                            cant_act = 0.0;
                        }
                        con.cerrar(rs);
                        con.cerrar(st);
                    } catch (SQLException ex) {
                        System.out.print(ex);
                    }

                    nueva_cant = cant_act - pro.getCan();

                    try {
                        Statement st = con.conexion();
                        String act_pro_alm = "Update producto_almacen set cant = '" + nueva_cant + "' where "
                                + "idAlmacen = '" + alm_or + "' and idProductos= '" + pro.getId_pro() + "'";
                        con.actualiza(st, act_pro_alm);
                        con.cerrar(st);
                    } catch (Exception ex) {
                        System.out.print(ex);
                    }

                    try {
                        Statement st = con.conexion();
                        String ins_kardex = "insert into kardex Values (null, '" + alb.getFecha() + "', '" + pro.getId_pro() + "', '0.00', '0.00', '" + pro.getCan() + "', '" + pro.getCos_pro() + "',"
                                + "'" + alb.getSer() + "', '" + alb.getNro() + "', '" + tido.getId() + "', '" + alm_or + "', '" + ruc + "', '" + almacen + "', '11')";
                        con.actualiza(st, ins_kardex);
                        con.cerrar(st);
                    } catch (Exception ex) {
                        System.out.print(ex);
                    }

                }

                //modificar numero de documento.
                tido.act_doc(tido.getSerie(), tido.getNro() + 1, frm_menu.alm.getId(), tido.getId());

            }
        }

        //imprimir detalle de envio
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("idtraslado", alb.getId());
        parametros.put("ruc", frm_menu.alm.getRuc());
        parametros.put("razon_social", frm_menu.alm.getRaz_soc());
        parametros.put("direccion", direccion_almacen(frm_menu.alm.getRuc()));
        parametros.put("tienda", cbx_alm_de.getSelectedItem().toString());
        ven.ver_reporte("rpt_ver_guia", parametros);

        btn_cer.doClick();
    }//GEN-LAST:event_btn_enviarActionPerformed

    private String direccion_almacen(String ruc) {
        String direccion = null;
        try {
            Statement st = con.conexion();
            String ver_alm = "select dir from empresa where ruc = '" + ruc + "'";
            ResultSet rs = con.consulta(st, ver_alm);
            if (rs.next()) {
                direccion = rs.getString("dir");
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (Exception e) {
            System.out.println(e);
        }
        return direccion;
    }


    private void cbx_alm_deKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_alm_deKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String almacen_destino = cbx_alm_de.getSelectedItem().toString();
            if (!almacen_destino.equals(frm_menu.alm.getNom())) {
                int idalm = cbx_alm_de.getSelectedIndex() + 1;
                datos_tienda(idalm);
                btn_transportista.setEnabled(true);
                btn_add.setEnabled(true);
                txt_buscar_producto.setEnabled(true);
                txt_buscar_producto.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUEDE SELECCIONAR EL MISMO ALMACEN");
            }
        }
    }//GEN-LAST:event_cbx_alm_deKeyPressed

    private void txt_fecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fecKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec.getText().trim().length() == 10) {
                cbx_alm_de.setEnabled(true);
                cbx_alm_de.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fecKeyPressed

    private void txt_fecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecActionPerformed

    private void btn_transportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transportistaActionPerformed
        jd_transportista.setSize(800, 300);
        jd_transportista.setModal(true);
        jd_transportista.setLocationRelativeTo(null);
        jd_transportista.setVisible(true);
    }//GEN-LAST:event_btn_transportistaActionPerformed

    private void cbx_documentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_documentoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int id_cbx_documentos = cbx_documento.getSelectedIndex() + 1;
            switch (cbx_documento.getSelectedItem().toString()) {
                case "GUIA DE REMISION":
                    tido.setSerie(tido.ver_ser(id_cbx_documentos, frm_menu.alm.getId()));
                    tido.setNro(tido.ver_num(id_cbx_documentos, frm_menu.alm.getId()));
                    txt_ser.setText(tido.getSerie() + "");
                    txt_num.setText(tido.getNro() + "");
                    txt_fec.setEnabled(true);
                    txt_fec.requestFocus();
                    break;
                case "NOTA DE SALIDA":
                    tido.setSerie(tido.ver_ser(id_cbx_documentos, frm_menu.alm.getId()));
                    tido.setNro(tido.ver_num(id_cbx_documentos, frm_menu.alm.getId()));
                    txt_ser.setText(tido.getSerie() + "");
                    txt_num.setText(tido.getNro() + "");
                    txt_fec.setEnabled(true);
                    txt_fec.requestFocus();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Error");
                    cbx_documento.setSelectedIndex(4);
                    break;
            }
        }
    }//GEN-LAST:event_cbx_documentoKeyPressed

    private void txt_motivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_motivoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_motivoKeyPressed

    private void txt_buscar_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_productoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            txt_buscar_producto.setText("");
            txt_buscar_producto.requestFocus();
        }
    }//GEN-LAST:event_txt_buscar_productoKeyPressed

    private void btn_recibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recibirActionPerformed
        if (accion.equals("verificar")) {
            btn_recibir.setEnabled(false);
            int alm_destino = frm_menu.alm.getId();
            int alm_origen = cbx_alm_de.getSelectedIndex() + 1;
            String ruc = txt_ruc_alm.getText().toUpperCase();
            String almacen = "DESDE TIENDA " + cbx_alm_de.getSelectedItem().toString();
            llenar();
            Integer filas = t_detalle.getRowCount();
            for (int x = 0; x < filas; x++) {
                pro.setId_pro(Integer.parseInt(t_detalle.getValueAt(x, 0).toString()));
                pro.setCan(Double.parseDouble(t_detalle.getValueAt(x, 6).toString()));
                double cantidad_enviada = Double.parseDouble(t_detalle.getValueAt(x, 4).toString());
                System.out.println(pro.getCan() + " - id: " + pro.getId_pro());

                try {
                    Statement st = con.conexion();
                    String ver_pre = "select precio_venta from Productos where idProductos  = '" + pro.getId_pro() + "'";
                    ResultSet rs = con.consulta(st, ver_pre);
                    System.out.println(ver_pre);
                    if (rs.next()) {
                        pro.setPre_pro(rs.getDouble("precio_venta"));
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }

                try {
                    Statement st = con.conexion();
                    String act_pro_alm = "Update productos_traslado set recibido = '" + pro.getCan() + "' where idtraslado = '" + idtras + "' and idProductos= '" + pro.getId_pro() + "'";
                    con.actualiza(st, act_pro_alm);
                    System.out.println(act_pro_alm);
                    con.cerrar(st);
                } catch (Exception ex) {
                    System.out.print(ex);
                }

                if (pro.getCan() > 0) {
                    //registrar ingreso al segundo almacen (actualizar cantidades)
                    boolean existe_producto = false;
                    try {
                        Statement st = con.conexion();
                        String ver_pro_alm = "select cant from producto_almacen where idAlmacen = '" + alm_destino + "' and idProductos= '" + pro.getId_pro() + "'";
                        ResultSet rs = con.consulta(st, ver_pro_alm);
                        System.out.println(ver_pro_alm);
                        if (rs.next()) {
                            System.out.println("almacen de destino: " + alm_destino + " Cambiando cantidad en almacen");
                            pro.setCan_act_pro(rs.getDouble("cant"));
                            pro.setCan_act_pro(pro.getCan_act_pro() + pro.getCan());
                            existe_producto = true;
                        } else {
                            System.out.println("almacen de destino: " + alm_destino + " ingresando producto a almacen");
                            pro.setCan_act_pro(0.0);
                            pro.setCan_act_pro(pro.getCan_act_pro() + pro.getCan());
                            existe_producto = false;
                        }
                        con.cerrar(rs);
                        con.cerrar(st);
                    } catch (SQLException ex) {
                        System.out.print(ex);
                    }

                    if (existe_producto) {
                        try {
                            Statement st = con.conexion();
                            String act_pro_alm = "Update producto_almacen set cant = '" + pro.getCan_act_pro() + "' where idAlmacen = '" + alm_destino + "' and idProductos= '" + pro.getId_pro() + "'";
                            con.actualiza(st, act_pro_alm);
                            System.out.println(act_pro_alm);
                            con.cerrar(st);
                        } catch (Exception ex) {
                            System.out.print(ex);
                        }
                    } else {
                        try {
                            Statement st = con.conexion();
                            String ins_pro_alm = "insert into producto_almacen Values ('" + pro.getId_pro() + "', '" + alm_destino + "', '" + pro.getCan_act_pro() + "', '" + pro.getPre_pro() + "')";
                            con.actualiza(st, ins_pro_alm);
                            System.out.println(ins_pro_alm);
                            con.cerrar(st);
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    }

                    try {
                        Statement st = con.conexion();
                        String ins_kardex = "insert into kardex Values (null, '" + alb.getFecha() + "', '" + pro.getId_pro() + "', '" + pro.getCan() + "', '" + pro.getPre_pro() + "', '0.00', '0.00', "
                                + "'" + alb.getSer() + "', '" + alb.getNro() + "', '" + tido.getId() + "', '" + alm_destino + "', '" + ruc + "', '" + almacen + "', '11')";
                        System.out.println(ins_kardex);
                        con.actualiza(st, ins_kardex);
                        con.cerrar(st);
                    } catch (Exception ex) {
                        System.out.print(ex);
                    }
                }

                if (pro.getCan() == 0 || pro.getCan() < cantidad_enviada) {
                    //devolver productos a tienda de origen siempre cuando cantidad aceptada 
                    // sea igual a 0 o cantidad es menor a la cantidad enviada

                    //buscar cantidad actual de productos en tienda origen
                    double cantidad_actual_origen = 0;
                    try {
                        Statement st = con.conexion();
                        String ver_pro_alm = "select cant from producto_almacen where idAlmacen = '" + alm_origen + "' and idProductos= '" + pro.getId_pro() + "'";
                        ResultSet rs = con.consulta(st, ver_pro_alm);
                        System.out.println(ver_pro_alm);
                        if (rs.next()) {
                            cantidad_actual_origen = rs.getDouble("cant");
                        }
                        con.cerrar(st);
                        con.cerrar(rs);
                    } catch (SQLException e) {
                        System.out.println(e.getLocalizedMessage());
                    }

                    double cantidad_regreso = cantidad_actual_origen - pro.getCan();

                    //actualizando cantidad actual de tienda de origen
                    try {
                        Statement st = con.conexion();
                        String act_pro_alm = "Update producto_almacen set cant = '" + cantidad_regreso + "' where idAlmacen = '" + alm_origen + "' and idProductos= '" + pro.getId_pro() + "'";
                        con.actualiza(st, act_pro_alm);
                        System.out.println(act_pro_alm);
                        con.cerrar(st);
                    } catch (Exception ex) {
                        System.out.print(ex);
                    }

                    //guardando cambio en kardex de productos tienda de origen
                    try {
                        Statement st = con.conexion();
                        String ins_kardex = "insert into kardex Values (null, '" + alb.getFecha() + "', '" + pro.getId_pro() + "', '0.00', '0.00', '" + pro.getCan() + "', '" + pro.getPre_pro() + "', "
                                + "'" + alb.getSer() + "', '" + alb.getNro() + "', '" + tido.getId() + "', '" + alm_origen + "', '" + ruc + "', '" + almacen + "', '11')";
                        System.out.println(ins_kardex);
                        con.actualiza(st, ins_kardex);
                        con.cerrar(st);
                    } catch (Exception ex) {
                        System.out.print(ex);
                    }

                }
            }

            try {
                Statement st = con.conexion();
                String upd_tra = "update traslado set estado = '1' where idTraslado = '" + idtras + "'";
                con.actualiza(st, upd_tra);
                System.out.println(upd_tra);
                con.cerrar(st);
            } catch (Exception e) {
                System.out.println(e);
            }

            btn_cer.doClick();
        }

    }//GEN-LAST:event_btn_recibirActionPerformed

    private void t_detalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_detalleMouseClicked
        if (evt.getClickCount() == 2) {
            if (accion.equals("verificar")) {
                int nro_fila = t_detalle.getSelectedRow();
                String id_producto = t_detalle.getValueAt(nro_fila, 0).toString();
                double cantidad_actual = Double.parseDouble(t_detalle.getValueAt(nro_fila, 4).toString());
                String texto = JOptionPane.showInputDialog("Ingrese Cantidad");
                double cantidad_nueva;
                if (texto != null) {
                    if (ven.esDecimal(texto)) {
                        cantidad_nueva = Double.parseDouble(texto);
                        if (cantidad_actual >= cantidad_nueva) {
                            t_detalle.setValueAt(ven.formato_numero(cantidad_nueva), nro_fila, 6);
                        } else {
                            double exceso = cantidad_nueva - cantidad_actual;
                            cantidad_nueva = cantidad_actual;
                            t_detalle.setValueAt(ven.formato_numero(cantidad_nueva), nro_fila, 6);
                            JOptionPane.showMessageDialog(null, "NO HAY DEMASIADOS PRODUCTOS \n EXCESO DE " + exceso + " UNIDADES");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_t_detalleMouseClicked

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        int cantidad_filas = t_detalle.getRowCount();
        int contar_ceros = 0;
        int contar_mayores = 0;
        for (int j = 0; j < cantidad_filas; j++) {
            double cantidad_aceptada = Double.parseDouble(t_detalle.getValueAt(j, 6).toString());
            double cantidad_recibida = Double.parseDouble(t_detalle.getValueAt(j, 4).toString());
            if (cantidad_aceptada == 0.0) {
                contar_ceros++;
            }
            if (cantidad_aceptada > cantidad_recibida) {
                JOptionPane.showMessageDialog(null, "Cantidad Aceptada no puede ser mayor a lo recibido en el Producto " + t_detalle.getValueAt(j, 1).toString());
                contar_mayores++;
            }
        }

        if (contar_ceros <= (cantidad_filas / 2) && contar_mayores == 0) {
            btn_recibir.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "ERROR!!: CANTIDAD CERO EN LA MAYORIA DE PRODUCTOS RECIBIDOS");
        }

    }//GEN-LAST:event_btn_verificarActionPerformed

    private void txt_busquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_busqueda.getText();
            String query = "select p.idProductos, p.desc_pro, p.modelo, p.serie, p.marca, pa.cant, p.cant_min, pa.precio, p.estado, c.desc_clas, "
                    + "u.desc_und, p.grado from producto_almacen as pa inner join productos as p on pa.idProductos=p.idProductos "
                    + "inner join clasificacion as c on p.id_clas=c.id_clas inner join und_medida as u on "
                    + "p.idUnd_Medida=u.idUnd_Medida where pa.idAlmacen = '" + frm_menu.alm.getId() + "' and (p.desc_pro like '%" + texto + "%' or p.modelo "
                    + "like '%" + texto + "%' or p.serie like '%" + texto + "%' or p.marca like '%" + texto + "%')  order by p.desc_pro asc, p.modelo asc";
            pro.mostrar_productos(query, t_productos);
            jLabel14.setText("" + tot_reg());
            t_productos.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            j_productos.dispose();
            txt_buscar_producto.requestFocus();
        }
    }//GEN-LAST:event_txt_busquedaKeyPressed

    private void txt_busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaKeyTyped

    }//GEN-LAST:event_txt_busquedaKeyTyped

    private int tot_reg() {
        int tot = 0;
        for (int j = 0; j < t_productos.getRowCount(); j++) {
            tot++;
        }
        return tot;
    }

    private void t_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_productosMouseClicked
        if (evt.getClickCount() == 2) {
        }
    }//GEN-LAST:event_t_productosMouseClicked

    private void t_productosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_productosMousePressed
        //        i = t_productos.getSelectedRow();
        //        btn_kar.setEnabled(true);
    }//GEN-LAST:event_t_productosMousePressed

    private void t_productosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_productosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int nro_fila = t_productos.getSelectedRow();
            String id_producto = t_productos.getValueAt(nro_fila, 0).toString();
            String descripcion = t_productos.getValueAt(nro_fila, 1).toString();
            String marca = t_productos.getValueAt(nro_fila, 2).toString();
            String und_med = t_productos.getValueAt(nro_fila, 4).toString();
            double cantidad = Double.parseDouble(t_productos.getValueAt(nro_fila, 3).toString());

            Object fila[] = new Object[7];
            fila[0] = id_producto;
            fila[1] = descripcion;
            fila[2] = marca;
            fila[3] = ven.formato_numero(cantidad);
            String texto = JOptionPane.showInputDialog("Ingrese Cantidad");
            double cantidad_nueva = 1;
            if (texto != null) {
                if (ven.esDecimal(texto)) {
                    cantidad_nueva = Double.parseDouble(texto);
                    //if (cantidad >= cantidad_nueva) {
                        fila[4] = ven.formato_numero(cantidad_nueva);
                 //   } else {
                 //       double exceso = cantidad_nueva - cantidad;
                   //     cantidad_nueva = cantidad;
                    //    fila[4] = ven.formato_numero(cantidad_nueva);
                    //    JOptionPane.showMessageDialog(null, "NO HAY DEMASIADOS PRODUCTOS \n EXCESO DE " + exceso + " UNIDADES");
                  //  }

                }
            }
            fila[5] = und_med;

            if (cantidad > 0.0) {
                valida_tabla(Integer.parseInt(id_producto), fila);
                txt_busqueda.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "No existe suficiente cantidad para agregar el producto.");
            }
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txt_busqueda.setText("");
            txt_busqueda.requestFocus();
        }
    }//GEN-LAST:event_t_productosKeyPressed

    private void btn_cer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cer1ActionPerformed
        j_productos.dispose();
    }//GEN-LAST:event_btn_cer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cc;
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_cer1;
    private javax.swing.JButton btn_el;
    public static javax.swing.JButton btn_enviar;
    public static javax.swing.JButton btn_recibir;
    private javax.swing.JButton btn_transportista;
    public static javax.swing.JButton btn_verificar;
    public static javax.swing.JComboBox cbx_alm_de;
    public static javax.swing.JComboBox cbx_documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog j_productos;
    private javax.swing.JDialog jd_transportista;
    public static javax.swing.JLabel lbl_tienda;
    private javax.swing.JRadioButton rbt_no;
    private javax.swing.JRadioButton rbt_si;
    public static javax.swing.JTable t_detalle;
    public static javax.swing.JTable t_productos;
    public static javax.swing.JTextField txt_brevete;
    private javax.swing.JTextField txt_buscar_producto;
    private javax.swing.JTextField txt_busqueda;
    public static javax.swing.JTextField txt_chofer1;
    public static javax.swing.JFormattedTextField txt_fec;
    public static javax.swing.JTextField txt_inscripcion;
    public static javax.swing.JTextField txt_llegada;
    public static javax.swing.JTextField txt_marca1;
    public static javax.swing.JTextField txt_modelo;
    public static javax.swing.JTextField txt_motivo;
    public static javax.swing.JTextField txt_num;
    public static javax.swing.JTextField txt_partida;
    public static javax.swing.JTextField txt_placa1;
    public static javax.swing.JTextField txt_raz_alm;
    public static javax.swing.JTextField txt_razon_transporte;
    public static javax.swing.JTextField txt_ruc_alm;
    public static javax.swing.JTextField txt_ruc_transporte;
    public static javax.swing.JTextField txt_ser;
    // End of variables declaration//GEN-END:variables
}
