/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sonomusic.frm_menu;

/**
 *
 * @author luis-d
 */
public class frm_configurar_documentos extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    DefaultTableModel modelo;
    int id;

    /**
     * Creates new form frm_conf_doc
     */
    public frm_configurar_documentos() {
        initComponents();
        txt_ser.requestFocus();
        cargar_doc();

    }

    private void cargar_doc() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        modelo.addColumn("Id");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Serie");
        modelo.addColumn("Nro");
        try {
            String query = "select td.idtipo_doc, td.desc_tipd as tipo_documento, da.ser_doc, da.nro_doc from documento_almacen as da inner join "
                    + "tipo_doc as td on da.idtipo_doc = td.idtipo_doc where da.idAlmacen = '"+frm_menu.alm.getId()+"'";
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);
            Object fila[] = new Object[4];
            while (rs.next()) {
                fila[0] = rs.getString("idtipo_doc");
                fila[1] = rs.getString("tipo_documento");
                fila[2] = rs.getString("ser_doc");
                fila[3] = rs.getString("nro_doc");
                /*String tipo = rs.getString("tipo_documento");
                if (tipo.equals("F")) {
                    fila[4] = "FISICO";
                }
                if (tipo.equals("E")) {
                    fila[4] = "ELECTRONICO";
                }*/
                modelo.addRow(fila);
            }
            t_documentos.setModel(modelo);
            t_documentos.getColumnModel().getColumn(0).setPreferredWidth(30);
            t_documentos.getColumnModel().getColumn(1).setPreferredWidth(100);
            t_documentos.getColumnModel().getColumn(2).setPreferredWidth(50);
            t_documentos.getColumnModel().getColumn(3).setPreferredWidth(70);
            ven.centrar_celda(t_documentos, 2);
            ven.centrar_celda(t_documentos, 3);
            con.cerrar(rs);
            con.cerrar(st);
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_ser = new javax.swing.JTextField();
        txt_nro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_documentos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();

        setTitle("Configurar Nro de Documentos");

        jLabel1.setText("Tipo y Nro. de Documento:");

        txt_ser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ser.setEnabled(false);
        txt_ser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serKeyPressed(evt);
            }
        });

        txt_nro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nro.setEnabled(false);
        txt_nro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nroKeyPressed(evt);
            }
        });

        jLabel5.setText("Serie");

        jLabel6.setText("Nro.");

        t_documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_documentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_documentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_documentos);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cross.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_mod.setText("Modificar");
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_mod)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_serKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_nro.requestFocus();
        }
    }//GEN-LAST:event_txt_serKeyPressed

    private void txt_nroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nroKeyPressed

    }//GEN-LAST:event_txt_nroKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_documentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_documentosMouseClicked
        if (evt.getClickCount() == 2) {
            int i = t_documentos.getSelectedRow();
            txt_ser.setText(t_documentos.getValueAt(i, 2).toString());
            txt_nro.setText(t_documentos.getValueAt(i, 3).toString());
            txt_ser.requestFocus();
            txt_ser.setEnabled(true);
            txt_nro.setEnabled(true);
            btn_mod.setEnabled(true);
            id = Integer.parseInt(t_documentos.getValueAt(i, 0).toString());
        }
    }//GEN-LAST:event_t_documentosMouseClicked

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        try {
            Statement st = con.conexion();
            String upd = "update documento_almacen set ser_doc = '" + txt_ser.getText() + "', nro_doc = '" + txt_nro.getText() + "' where "
                    + "idtipo_doc = '" + id + "' and idalmacen = '" + frm_menu.alm.getId()+ "'";
            con.actualiza(st, upd);
            con.cerrar(st);
            btn_mod.setEnabled(false);
            txt_ser.setText("");
            txt_nro.setText("");
            txt_ser.setEnabled(false);
            txt_nro.setEnabled(false);
            cargar_doc();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btn_modActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_documentos;
    private javax.swing.JTextField txt_nro;
    private javax.swing.JTextField txt_ser;
    // End of variables declaration//GEN-END:variables
}
