/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Cl_Conectar;
import Clases.Cl_Tipo_Documentos;
import java.awt.event.KeyEvent;
import sonomusic.frm_menu;

/**
 *
 * @author luis-d
 */
public class frm_conf_doc extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Tipo_Documentos tido = new Cl_Tipo_Documentos();

    /**
     * Creates new form frm_conf_doc
     */
    public frm_conf_doc() {
        initComponents();
        ver_nota();
        ver_boleta();
        ver_factura();
        ver_guia();
        txt_ser_nota.requestFocus();
    }

    private void ver_nota() {
        int idalm = frm_menu.alm.getId();
        int idtido = 1;
        txt_ser_nota.setText("" + tido.ver_ser(idtido, idalm));
        txt_nro_nota.setText("" + tido.ver_num(idtido, idalm));
    }

    private void ver_boleta() {
        int idalm = frm_menu.alm.getId();
        int idtido = 2;
        txt_ser_bol.setText("" + tido.ver_ser(idtido, idalm));
        txt_nro_bol.setText("" + tido.ver_num(idtido, idalm));
    }

    private void ver_factura() {
        int idalm = frm_menu.alm.getId();
        int idtido = 3;
        txt_ser_fac.setText("" + tido.ver_ser(idtido, idalm));
        txt_nro_fac.setText("" + tido.ver_num(idtido, idalm));
    }

    private void ver_guia() {
        int idalm = frm_menu.alm.getId();
        int idtido = 4;
        txt_ser_guia.setText("" + tido.ver_ser(idtido, idalm));
        txt_nro_guia.setText("" + tido.ver_num(idtido, idalm));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ser_nota = new javax.swing.JTextField();
        txt_ser_bol = new javax.swing.JTextField();
        txt_ser_fac = new javax.swing.JTextField();
        txt_ser_guia = new javax.swing.JTextField();
        txt_nro_nota = new javax.swing.JTextField();
        txt_nro_bol = new javax.swing.JTextField();
        txt_nro_fac = new javax.swing.JTextField();
        txt_nro_guia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setClosable(true);
        setForeground(new java.awt.Color(255, 0, 0));
        setTitle("Configurar Nro de Documentos");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TIPO Y NRO. DE DOCUMENTO:");

        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        btn_reg.setText("Registrar");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        btn_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_regKeyPressed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(229, 59, 59));
        jLabel7.setText("Nota de Venta:");

        jLabel8.setForeground(new java.awt.Color(229, 59, 59));
        jLabel8.setText("Boleta:");

        jLabel9.setForeground(new java.awt.Color(229, 59, 59));
        jLabel9.setText("Factura:");

        jLabel10.setForeground(new java.awt.Color(229, 59, 59));
        jLabel10.setText("Guia de Remision:");

        txt_ser_nota.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_ser_bol.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_ser_fac.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_ser_guia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_nro_nota.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_nro_bol.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_nro_fac.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_nro_guia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("Serie");

        jLabel3.setText("Nro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_reg))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txt_ser_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ser_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ser_guia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ser_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txt_nro_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nro_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nro_guia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nro_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ser_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nro_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ser_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nro_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ser_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nro_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ser_guia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nro_guia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        int serie;
        int nro;
        int alm = frm_menu.alm.getId();
        int doc;
        // ACTUALIZAR NOTA DE VENTA
        try {
            serie = Integer.parseInt(txt_ser_nota.getText());
            nro = Integer.parseInt(txt_nro_nota.getText());
            doc = 1;
            tido.act_doc(serie, nro, alm, doc);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        // ACTUALIZAR BOLETA
        try {
            serie = Integer.parseInt(txt_ser_bol.getText());
            nro = Integer.parseInt(txt_nro_bol.getText());
            doc = 2;
            tido.act_doc(serie, nro, alm, doc);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        // ACTUALIZAR FACTURA
        try {
            serie = Integer.parseInt(txt_ser_fac.getText());
            nro = Integer.parseInt(txt_nro_fac.getText());
            doc = 3;
            tido.act_doc(serie, nro, alm, doc);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        // ACTUALIZAR GUIA DE REMISION
        try {
            serie = Integer.parseInt(txt_ser_guia.getText());
            nro = Integer.parseInt(txt_nro_guia.getText());
            doc = 4;
            tido.act_doc(serie, nro, alm, doc);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_regKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_reg.doClick();
        }
    }//GEN-LAST:event_btn_regKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_nro_bol;
    private javax.swing.JTextField txt_nro_fac;
    private javax.swing.JTextField txt_nro_guia;
    private javax.swing.JTextField txt_nro_nota;
    private javax.swing.JTextField txt_ser_bol;
    private javax.swing.JTextField txt_ser_fac;
    private javax.swing.JTextField txt_ser_guia;
    private javax.swing.JTextField txt_ser_nota;
    // End of variables declaration//GEN-END:variables
}
