/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Cargo;
import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis-d
 */
public class frm_cargos extends javax.swing.JInternalFrame {
    Cl_Varios ven = new Cl_Varios();
    Cl_Conectar con = new Cl_Conectar();
    Cl_Cargo car = new Cl_Cargo();
    DefaultTableModel mostrar;
    Integer i;
    /**
     * Creates new form frm_cargos
     */
    public frm_cargos() {
        initComponents();
        
        txt_desc.requestFocus();
        String query = "select * from cargo order by tipo_cargo asc";
        ver_cargo(query);
        
    }

    
    private void ver_cargo (String query){
      try {
        mostrar = new DefaultTableModel()
 {@Override
     public boolean isCellEditable (int fila, int columna) {
         return false;
     }
 };
        Statement st= con.conexion();
        ResultSet rs = con.consulta(st, query);
        //Establecer como cabezeras el nombre de las colimnas
        mostrar.addColumn("Id");
        mostrar.addColumn("Descripcion");
        
        //Creando las filas para el JTable
        while (rs.next()) {
            Object[] fila = new Object[2];
            fila[0]=rs.getObject("idCargo");
            fila[1]=rs.getObject("tipo_cargo");

            mostrar.addRow(fila);
        }
        con.cerrar(st);
        con.cerrar(rs);
        t_cargo.setModel(mostrar);
        t_cargo.getColumnModel().getColumn(0).setPreferredWidth(20);
        t_cargo.getColumnModel().getColumn(1).setPreferredWidth(250);
        mostrar.fireTableDataChanged();
    }
    catch (SQLException e) {
        System.out.print(e);
    }
              
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_reg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_cer1 = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_cargo = new javax.swing.JTable();
        txt_desc = new javax.swing.JTextField();
        btn_gra = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ver Cargos");

        jLabel2.setText("Descripcion:");
        jLabel2.setFocusable(false);

        txt_id.setEditable(false);

        btn_reg.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_add.png"))); // NOI18N
        btn_reg.setText("Registrar");
        btn_reg.setMargin(new java.awt.Insets(3, 3, 3, 3));
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        btn_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_regKeyPressed(evt);
            }
        });

        jLabel1.setText("Id:");
        jLabel1.setFocusable(false);

        btn_cer1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_cer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer1.setText("Cerrar");
        btn_cer1.setFocusable(false);
        btn_cer1.setMargin(new java.awt.Insets(3, 3, 3, 3));
        btn_cer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cer1ActionPerformed(evt);
            }
        });

        btn_mod.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_edit.png"))); // NOI18N
        btn_mod.setText("Modificar");
        btn_mod.setEnabled(false);
        btn_mod.setFocusable(false);
        btn_mod.setMargin(new java.awt.Insets(3, 3, 3, 3));
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        jScrollPane1.setFocusable(false);

        t_cargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_cargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_cargoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_cargo);

        txt_desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descKeyPressed(evt);
            }
        });

        btn_gra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_gra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_edit.png"))); // NOI18N
        btn_gra.setText("Grabar");
        btn_gra.setEnabled(false);
        btn_gra.setFocusable(false);
        btn_gra.setMargin(new java.awt.Insets(3, 3, 3, 3));
        btn_gra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_reg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn_cer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_gra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_desc)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_gra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btn_cer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenar () {
        car.setDescripcion(txt_desc.getText());
    }
    
    private void btn_cer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cer1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cer1ActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        llenar();
        if (!txt_desc.getText().isEmpty()) {
        Statement st = con.conexion();
        String ins_car = "insert into cargo Values (null, '"+car.getDescripcion()+"')";
        con.actualiza(st, ins_car);
        con.cerrar(st);
        txt_desc.setText("");
        txt_desc.requestFocus();
        car.setDescripcion("");
        String query = "select * from cargo order by tipo_cargo asc";
        ver_cargo(query);
        } else {
            JOptionPane.showMessageDialog(null, "No hay ningun dato");
            txt_desc.setText("");
            txt_desc.requestFocus();
        }
    }//GEN-LAST:event_btn_regActionPerformed

    private void txt_descKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (!txt_desc.getText().isEmpty()) {
                btn_reg.setEnabled(true);
                btn_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_descKeyPressed

    private void btn_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_regKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            btn_reg.doClick();
        }
    }//GEN-LAST:event_btn_regKeyPressed

    private void t_cargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cargoMousePressed
        i = t_cargo.getSelectedRow();
        btn_mod.setEnabled(true);
    }//GEN-LAST:event_t_cargoMousePressed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        btn_reg.setEnabled(false);
        car.setId(Integer.parseInt(t_cargo.getValueAt(i, 0).toString()));
        car.setDescripcion(t_cargo.getValueAt(i, 1).toString());
        txt_id.setText(""+car.getId());
        txt_desc.setText(car.getDescripcion());
        btn_mod.setEnabled(false);
        btn_gra.setEnabled(true);
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_graActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graActionPerformed
        llenar ();
        Statement st = con.conexion();
        String upd_car = "update cargo set tipo_cargo = '"+car.getDescripcion()+"' where idCargo = '"+car.getId()+"'";
        con.actualiza(st, upd_car);
        con.cerrar(st);
        txt_desc.setText("");
        txt_desc.requestFocus();
        car.setDescripcion("");
        txt_id.setText("");
        String query = "select * from cargo order by tipo_cargo asc";
        ver_cargo(query);
        btn_reg.setEnabled(true);
        btn_mod.setEnabled(false);
        btn_gra.setEnabled(false);
    }//GEN-LAST:event_btn_graActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer1;
    private javax.swing.JButton btn_gra;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_cargo;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
