/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import sonomusic.frm_menu;

/**
 *
 * @author Dereck
 */
public class frm_mov_bancos extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();

    /**
     * Creates new form frm_mov_bancos
     */
    public frm_mov_bancos() {
        initComponents();
        ver_bancos();

    }

    private void ver_bancos() {
        try {
            ArrayList banco = new ArrayList();
            Statement st = con.conexion();
            String query = "select nombre from banco order by idbanco asc";
            ResultSet rs = con.consulta(st, query);
            while (rs.next()) {
                banco.add(rs.getString("nombre"));
            }
            if (banco.size() > 0) {
                for (int j = 0; j < banco.size(); j++) {
                    cbx_banco.addItem(banco.get(j));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Lista de Bancos no disponible");
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, "Lista no disponible");
        }
    }

    private void ver_nro_cuenta(int idban) {

        try {
            ArrayList cuenta = new ArrayList();
            Statement st = con.conexion();
            String query = "select nro_cuenta from cuenta where idbanco = '" + idban + "' order by idcuenta asc";
            ResultSet rs = con.consulta(st, query);
            while (rs.next()) {
                cuenta.add(rs.getString("nro_cuenta"));
            }
            if (cuenta.size() > 0) {
                cbx_cuenta.removeAllItems();
                for (int j = 0; j < cuenta.size(); j++) {
                    cbx_cuenta.addItem(cuenta.get(j));
                }
            } else {
                cbx_cuenta.removeAllItems();
                JOptionPane.showMessageDialog(null, "cuenta no disponible");
                cbx_cuenta.setEnabled(false);
                cbx_banco.requestFocus();
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cer = new javax.swing.JButton();
        btn_ini = new javax.swing.JButton();
        cbx_banco = new javax.swing.JComboBox();
        cbx_cuenta = new javax.swing.JComboBox();
        txt_fec_ini = new javax.swing.JFormattedTextField();
        txt_fec_fin = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Movimiento por Banco");

        jLabel1.setText("Seleccion de Bancos - Movimientos");

        jLabel2.setText("Banco:");

        jLabel3.setText("Cuenta:");

        jLabel4.setText("Fecha Inicio:");

        jLabel5.setText("Fecha Fin:");

        btn_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        btn_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        btn_ini.setText("Iniciar");
        btn_ini.setEnabled(false);
        btn_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniActionPerformed(evt);
            }
        });
        btn_ini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_iniKeyPressed(evt);
            }
        });

        cbx_banco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_bancoKeyPressed(evt);
            }
        });

        cbx_cuenta.setEnabled(false);
        cbx_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_cuentaKeyPressed(evt);
            }
        });

        txt_fec_ini.setEditable(false);
        try {
            txt_fec_ini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_ini.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_ini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_iniKeyPressed(evt);
            }
        });

        txt_fec_fin.setEditable(false);
        try {
            txt_fec_fin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_fin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_fin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_finKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbx_cuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_banco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fec_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fec_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ini)
                        .addGap(18, 18, 18)))
                .addComponent(btn_cer)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fec_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fec_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fec_iniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_iniKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_ini.getText().trim().length() == 10) {
                txt_fec_fin.setEditable(true);
                txt_fec_fin.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fec_iniKeyPressed

    private void txt_fec_finKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_finKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_ini.setEnabled(true);
            btn_ini.requestFocus();
        }
    }//GEN-LAST:event_txt_fec_finKeyPressed

    private void cbx_bancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_bancoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int idban = cbx_banco.getSelectedIndex() + 1;
            ver_nro_cuenta(idban);
            cbx_cuenta.setEnabled(true);
            cbx_cuenta.requestFocus();
        }
    }//GEN-LAST:event_cbx_bancoKeyPressed

    private void cbx_cuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_cuentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_fec_ini.setEditable(true);
            txt_fec_ini.requestFocus();
        }
    }//GEN-LAST:event_cbx_cuentaKeyPressed

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void btn_iniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_iniKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_ini.doClick();
        }
    }//GEN-LAST:event_btn_iniKeyPressed

    private void btn_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniActionPerformed
        String fec_ini = ven.fechabase(txt_fec_ini.getText());
        String fec_fin = ven.fechabase(txt_fec_fin.getText());
        String cuenta = cbx_cuenta.getSelectedItem().toString();
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("fec_mov", fec_ini);
        parametros.put("fec_ini", fec_fin);
        parametros.put("cuenta", cuenta);
        ven.ver_reporte("rpt_caja_movimiento_bancos", parametros);
        this.dispose();
    }//GEN-LAST:event_btn_iniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_ini;
    private javax.swing.JComboBox cbx_banco;
    private javax.swing.JComboBox cbx_cuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField txt_fec_fin;
    private javax.swing.JFormattedTextField txt_fec_ini;
    // End of variables declaration//GEN-END:variables
}
