/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Conectar;
import Clases.Cl_Nota;
import Clases.Cl_Varios;
import Forms.frm_reg_nota;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis-d
 */
public class frm_ver_notas extends javax.swing.JInternalFrame {
Cl_Conectar con = new Cl_Conectar();
Cl_Varios ven = new Cl_Varios();
Cl_Nota nota = new Cl_Nota();
Integer i;
DefaultTableModel mostrar ;
    /**
     * Creates new form frm_ver_notas
     */
    public frm_ver_notas() {
        initComponents();
        
        String query ="select * from notas where estado = '0' order by idNotas desc";
        ver_nota(query);
    }

    private void ver_nota(String query) {
         try {
        mostrar = new DefaultTableModel()
 {@Override
     public boolean isCellEditable (int fila, int columna) {
         return false;
     }
 };
        Statement st= con.conexion();
        ResultSet rs = con.consulta(st, query);
       
        //Establecer como cabezeras el nombre de las colimnas
        mostrar.addColumn("Id");
        mostrar.addColumn("Fecha Reg.");
        mostrar.addColumn("Fecha Eje.");
        mostrar.addColumn("Descripcion");
        mostrar.addColumn("Usuario");
        mostrar.addColumn("Estado");
        
        //Creando las filas para el JTable
        while (rs.next()) {
            Object[] fila = new Object[6];
            fila[0]=rs.getObject("idNotas");
            fila[1]=rs.getObject("fecha_reg");
            fila[2]=rs.getObject("fecha_eje");
            fila[3]=rs.getObject("glosa");
            fila[4]=rs.getObject("nick");
            String estado = rs.getString("estado");
            if (estado.equals("0")) {
                fila[5]="Pendiente";
            } else {
                fila[5]="Relizado";
            }
            

            mostrar.addRow(fila);
        }
        con.cerrar(st);
        con.cerrar(rs);
        t_notas.setModel(mostrar);
        t_notas.getColumnModel().getColumn(0).setPreferredWidth(30);
        t_notas.getColumnModel().getColumn(1).setPreferredWidth(80);
        t_notas.getColumnModel().getColumn(2).setPreferredWidth(80);
        t_notas.getColumnModel().getColumn(3).setPreferredWidth(350);
        t_notas.getColumnModel().getColumn(4).setPreferredWidth(80);
        t_notas.getColumnModel().getColumn(5).setPreferredWidth(90);
        mostrar.fireTableDataChanged();
    }
    catch (SQLException e) {
        System.out.print(e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_notas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btn_fin = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        cbx_estado = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(254, 254, 254));
        setClosable(true);
        setTitle("Ver Notas / Notificaciones");

        jLabel1.setForeground(new java.awt.Color(212, 2, 2));
        jLabel1.setText("Buscar:");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));

        t_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_notas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_notasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_notas);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_fin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comment.png"))); // NOI18N
        btn_fin.setText("Realizado");
        btn_fin.setEnabled(false);
        btn_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finActionPerformed(evt);
            }
        });

        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/page.png"))); // NOI18N
        btn_ver.setText("Ver Nota");
        btn_ver.setEnabled(false);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        cbx_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendiente", "Realizado ", "Todos" }));
        cbx_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbx_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_fin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    frm_reg_nota notas = new frm_reg_nota();
    ven.llamar_ventana(notas);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_notasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_notasMousePressed
    i = t_notas.getSelectedRow();
    btn_ver.setEnabled(true);
    String Estado; 
    Estado = t_notas.getValueAt(i, 5).toString();
    if (Estado.equals("Pendiente")) {
        btn_fin.setEnabled(true);
    } else {
        btn_fin.setEnabled(false);
    }
    }//GEN-LAST:event_t_notasMousePressed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        nota.setId(Integer.parseInt(t_notas.getValueAt(i, 0).toString()));
        try {
            Statement st = con.conexion();
            String det_nota = "select glosa from Notas where idNotas = '"+nota.getId()+"'";
            ResultSet rs = con.consulta(st, det_nota);
            if (rs.next()) {
                frm_reg_nota notas = new frm_reg_nota();
                notas.txt_nota.setText(rs.getString("glosa"));
                notas.txt_nota.setEditable(false);
                notas.btn_reg.setEnabled(false);
                ven.llamar_ventana(notas);
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (SQLException ex) {
            System.out.print(ex);
        }
        
    }//GEN-LAST:event_btn_verActionPerformed

    private void btn_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finActionPerformed
    int confirmado = JOptionPane.showConfirmDialog( null, "¿Confirma la accion?");
    nota.setFec_eje(ven.getFechaActual());
    nota.setId(Integer.parseInt(t_notas.getValueAt(i, 0).toString()));
    if (JOptionPane.OK_OPTION == confirmado) {
        try {
            Statement st = con.conexion();
            String query = "update Notas set fecha_eje = '"+nota.getFec_eje()+"', estado = '1' where idNotas = '"+nota.getId()+"'";
            con.actualiza(st, query);
            con.cerrar(st);
            String ver_notas ="select * from Notas where estado = '0' order by idNotas desc";
            ver_nota(ver_notas);
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }
    }//GEN-LAST:event_btn_finActionPerformed

    private void cbx_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_estadoActionPerformed
        if (cbx_estado.getSelectedIndex()==0) {
        String ver_notas ="select * from Notas where estado = '0' order by idNotas desc";
        ver_nota(ver_notas); }
        
        if (cbx_estado.getSelectedIndex()==1) {
        String ver_notas ="select * from Notas where estado = '1' order by idNotas desc";
        ver_nota(ver_notas); }
        
        if (cbx_estado.getSelectedIndex()==2) {
        String ver_notas ="select * from Notas order by idNotas desc";
        ver_nota(ver_notas); }
    }//GEN-LAST:event_cbx_estadoActionPerformed

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String bus = txt_bus.getText();
            String query = "select * from notas where glosa like '%" + bus + "%' or nick like '%" + bus + "%'"
                         + " order by fecha_reg";
            ver_nota(query);
        }
    }//GEN-LAST:event_txt_busKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fin;
    private javax.swing.JButton btn_ver;
    private javax.swing.JComboBox cbx_estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_notas;
    private javax.swing.JTextField txt_bus;
    // End of variables declaration//GEN-END:variables
}
