/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author RRHH
 */
public class frm_sel_periodo extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    public static String origen = "";
    public static String rpt = "";
    public static String ruc = "";

    /**
     * Creates new form frm_sel_mes
     */
    public frm_sel_periodo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        txt_periodo = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Seleccionar Periodo");
        setToolTipText("");

        jLabel1.setText("Seleccionar Mes");

        btn_ok.setText("Aceptar");
        btn_ok.setEnabled(false);
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        try {
            txt_periodo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_periodo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_periodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_periodoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        String per = txt_periodo.getText();
        String mes_periodo = per.charAt(0) + "" + per.charAt(1);
        String anio_periodo = per.charAt(3) + "" + per.charAt(4) + "" + per.charAt(5) + "" + per.charAt(6);

        //REPORTES SUNAT
        if (rpt.equals("compra_empresa")) {
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("periodo", per);
            parametros.put("ruc", ruc);
            ven.ver_reporte("rpt_compras", parametros);

        }

        if (rpt.equals("rpt_ventas_empresa")) {
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("mes", mes_periodo);
            parametros.put("anio_periodo", anio_periodo);
            parametros.put("ruc", ruc);
            ven.ver_reporte("rpt_ventas", parametros);
        }

        this.dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    private void txt_periodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_periodoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_periodo.getText().length() == 7) {
                btn_ok.setEnabled(true);
                btn_ok.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_periodoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField txt_periodo;
    // End of variables declaration//GEN-END:variables
}
